dinner_guests = ['Bob Marley', 'Cleopatra', 'George Harrison', 'Marlon Brando']
print(f"Hello: {dinner_guests[0]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[1]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[2]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[3]}, you are invited to dinner with me!")
print("Oh no! Cleopatra can't make it, I better invite sombody else.")
del dinner_guests[1]
print(dinner_guests)
dinner_guests.append('Elvis Presley')
print(f"Hello: {dinner_guests[0]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[1]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[2]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[3]}, you are invited to dinner with me!")
print("I've found a bigger table!!")

dinner_guests.insert(0,'James Bond')
dinner_guests.insert(3,'Mick Hutnal')
dinner_guests.append('Michael Angelo')
print(dinner_guests)
print(f"Hello: {dinner_guests[0]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[1]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[2]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[3]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[4]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[5]}, you are invited to dinner with me!")
print(f"Hello: {dinner_guests[6]}, you are invited to dinner with me!")

print("Ah shite, I can only take 2 on this tiny table")
print(dinner_guests)
removed = dinner_guests.pop(0)
print(f"Sorry {removed}, you're out of here!")
removed = dinner_guests.pop(0)
print(f"Sorry {removed}, you're out of here!")
removed = dinner_guests.pop(0)
print(f"Sorry {removed}, you're out of here!")
removed = dinner_guests.pop(0)
print(f"Sorry {removed}, you're out of here!")
removed = dinner_guests.pop(0)
print(f"Sorry {removed}, you're out of here!")
print(f"Don't worry {dinner_guests[0]} and {dinner_guests[1]}, you both can still come along.")
del dinner_guests[0]
del dinner_guests[0]
print(dinner_guests)
